server/fvlogging/datalog/urls.py
from django.conf.urls import url
import datalog.views

# Consider updating to django paths

urlpatterns = [
    # Main index page
    url(r'^$', datalog.views.summary),
    url(r'^detail/(?P<name>\w+)/$', datalog.views.detail,
        name="datalog-controller"),
    url(r'^detail/(?P<name>\w+)/config/$', datalog.views.detail,
        {'config': True}, name="datalog-controller-config"),
    url(r'^detail/(?P<name>\w+)/graph/$', datalog.views.detailgraph,
        name="datalog-detailgraph"),
    url(r'^detail/(?P<name>\w+)/graph/(?P<start>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d)--(?P<end>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d)$',  # noqa: E501
        datalog.views.detailgraph, name="datalog-detailgraph-period"),
    url(r'^series/(?P<name>\w+)-(?P<register>\w+/?\w*).csv$',
        datalog.views.series_csv, name="datalog-csvfile"),
    url(r'^graph.svg', datalog.views.graph, name="datalog-graph"),
]

server/fvlogging/fvlogging/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.admindocs.urls
import fvlogging.views
import datalog.urls
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'fvlogging.views.home', name='home'),
    # url(r'^fvlogging/', include('fvlogging.foo.urls')),

    url(r'^$', fvlogging.views.frontpage),

    url(r'^datalog/', include(datalog.urls.urlpatterns)),

    url(r'^admin/doc/', include(django.contrib.admindocs.urls)),
    url(r'^admin/', admin.site.urls),
]

server/fvlogging/datalog/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.shortcuts import render
from django import forms
from django.urls import reverse
from datalog.models import Controller, Register, DATATYPE_DICT
import datetime
import csv
import xml.etree.ElementTree as ET


def summary(request):
    controllers = Controller.objects.all()
    registers = Register.objects.filter(frontpage=True)\
                                .order_by("description")\
                                .all()
    return render(request, 'datalog/summary.html',
                  context={'controllers': controllers,
                           'registers': registers})


class FutureChangeForm(forms.Form):
    after = forms.DateTimeField(required=False, label="Set values after")


def detail(request, name, config=False):
    try:
        controller = Controller.objects.get(ident=name)
    except Controller.DoesNotExist:
        raise Http404
    registers = controller.register_set.filter(config=config)
    extraseries = Register.objects.exclude(graphcolour_all="")

    if request.method == 'POST':
        fcform = FutureChangeForm(request.POST)
        if fcform.is_valid():
            after = fcform.cleaned_data['after']
            for r in registers:
                if 'set' in request.POST:
                    if r.name in request.POST and request.POST[r.name]:
                        if after:
                            r.future_value = request.POST[r.name]
                            r.future_time = after
                            r.save()
                        else:
                            r.set(request.POST[r.name])
                elif 'clear' in request.POST:
                    r.future_value = None
                    r.future_time = None
                    r.save()
            return HttpResponseRedirect(
                reverse('datalog-controller-config' if config
                        else 'datalog-controller',
                        args=(name,)))
    else:
        fcform = FutureChangeForm()

    return render(
        request, 'datalog/detail.html', context={
            'controller': controller,
            'registers': registers,
            'extraseries': extraseries,
            'config': config,
            'fcform': fcform,
        })


class GraphPeriodForm(forms.Form):
    start = forms.DateTimeField()
    end = forms.DateTimeField()

    def clean(self):
        s = None
        e = None
        try:
            s = self.cleaned_data['start']
            e = self.cleaned_data['end']
        except Exception:
            pass
        if s and e and e <= s:
            raise forms.ValidationError("Start must be before end")
        return self.cleaned_data


def detailgraph(request, name, start=None, end=None):
    try:
        controller = Controller.objects.get(ident=name)
    except Controller.DoesNotExist:
        raise Http404
    extraseries = Register.objects.exclude(graphcolour_all="")
    if start is None or end is None:
        end = datetime.datetime.now().replace(microsecond=0)
        start = end - datetime.timedelta(days=7)
    else:
        start = parsedatetime(start)
        end = parsedatetime(end)

    if request.method == 'POST':
        form = GraphPeriodForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            start = cd['start']
            end = cd['end']
            return HttpResponseRedirect(
                reverse('datalog-detailgraph-period',
                        args=(name, str(start), str(end))))
    else:
        form = GraphPeriodForm(initial={
            'start': start,
            'end': end,
        })

    period = end - start

    return render(request, 'datalog/detailgraph.html',
                  context={'controller': controller,
                           'extraseries': extraseries,
                           'form': form,
                           'start': str(start),
                           'end': str(end),
                           'period': period,
                           'back': str(start - period),
                           'forward': str(end + period),
                           })


def series_csv(request, name, register):
    try:
        controller = Controller.objects.get(ident=name)
    except Controller.DoesNotExist:
        raise Http404
    try:
        register = controller.register_set.get(name=register)
    except Register.DoesNotExist:
        raise Http404
    dt = DATATYPE_DICT[register.datatype]
    series = dt.objects.filter(register=register).order_by('timestamp')
    r = HttpResponse(content_type="text/csv")
    r['Content-Disposition'] = 'attachment; filename=%s-%s.csv' % (
        controller.ident, register.name.replace('/', '-'))
    c = csv.writer(r)
    for d in series:
        c.writerow((d.timestamp.strftime("%Y-%m-%d %H:%M:%S"), d.data))
    return r


def parsedatetime(d):
    """Convert a string to a datetime object

    Tries several possible format strings in order.  Returns the first
    match, or None.
    """
    formats = ('%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%Y-%m-%d')
    for f in formats:
        try:
            return datetime.datetime.strptime(d, f)
        except ValueError:
            pass
    return None


def graph(request):
    """Draw a graph.  Time will always be along the x axis.

    The request can have the following parameters:
    width - width of returned image, defaults to 800
    height - height of returned image, defaults to 600
    end - end date and time in ISO format, defaults to now
    start - start date and time in ISO format (yyyy-mm-dd hh:mm:ss)
    (start defaults to end-1 day)
      - or a time difference
    title - title of graph
    series - a data series to plot, as follows:
      controller:register:colour
    """
    width = int(request.GET.get('width', 800))
    height = int(request.GET.get('height', 600))
    leftmargin = int(request.GET.get('leftmargin', 100))
    bottommargin = int(request.GET.get('bottommargin', 100))
    floatmin = float(request.GET.get('floatmin', 0.0))
    floatmax = float(request.GET.get('floatmax', 30.0))
    end = None
    if 'end' in request.GET:
        end = parsedatetime(request.GET['end'])
    if end is None:
        end = datetime.datetime.now()
        start = None
    if 'start' in request.GET:
        start = parsedatetime(request.GET['start'])
        if start is None:
            try:
                start = end - datetime.timedelta(
                    days=int(request.GET['start']))
            except ValueError:
                pass
    if start is None:
        start = end - datetime.timedelta(days=30)

    length = (end - start).total_seconds()
    series = request.GET.getlist('series')

    # Origin is in top-left by default.
    svg = ET.Element("svg", {'xmlns': 'http://www.w3.org/2000/svg',
                             'version': '1.1',
                             'width': str(width),
                             'height': str(height)})
    ET.SubElement(svg, "title").text = "A Graph"
    ET.SubElement(svg, "desc").text = "A longer description of the group"
    # Bounding box
    ET.SubElement(svg, "rect", x="0", y="0",
                  width=str(width), height=str(height),
                  fill="none", stroke="blue")

    # Let's create a group with a transformed coordinate space such
    # that the origin is in the bottom-left
    g = ET.SubElement(svg, "g", transform="translate(%d,%d) scale(1,-1)" % (
        leftmargin, height - bottommargin))

    # We now can draw axes, etc. from 0 - (width - leftmargin) on X
    # and 0 - (height - bottommargin) on y
    graphwidth = width - leftmargin
    graphheight = height - bottommargin

    # Draw horizontal scale lines for temperature
    y = 0.0
    while y < floatmax:
        scaley = (y - floatmin) * graphheight / floatmax
        ET.SubElement(g, "line", x1="0", x2=str(width),
                      y1=str(scaley), y2=str(scaley),
                      stroke="lightgrey")
        y = y + 1.0
    y = 0.0
    while y < floatmax:
        scaley = (y - floatmin) * graphheight / floatmax
        ET.SubElement(g, "line", x1="0", x2=str(width),
                      y1=str(scaley), y2=str(scaley),
                      stroke="darkgrey")
        y = y + 5.0

    for s in series:
        controller, register, colour = s.split(":")
        controller = Controller.objects.get(ident=controller)
        register = Register.objects.get(controller=controller, name=register)
        # Retrieve all datapoints between start and end
        dt = DATATYPE_DICT[register.datatype]
        # We want to find the timestamps of the first datapoint before
        # start (if there is one) and the first datapoint after end
        # (if there is one), and adjust start and end to include
        # these.  This will avoid the graph having blank sections at
        # the left and right hand sides.
        sdp = dt.objects.filter(register=register, timestamp__lt=start)\
                        .order_by('-timestamp')[:1]
        s_start = sdp[0].timestamp if len(sdp) == 1 else start
        edp = dt.objects.filter(register=register, timestamp__gt=end)\
                        .order_by('timestamp')[:1]
        s_end = edp[0].timestamp if len(edp) == 1 else end
        datapoints = dt.objects.filter(register=register, timestamp__lte=s_end,
                                       timestamp__gte=s_start)\
                               .order_by('timestamp')
        now_drawing = False
        dl = []
        for datum in datapoints:
            x = (datum.timestamp - start).total_seconds() * graphwidth / length
            if datum.data is None:
                now_drawing = False
            else:
                # Let's assume float for now
                y = (datum.data - floatmin) * graphheight / floatmax
                dl.append("%s %f %f" % ('L' if now_drawing else 'M', x, y))

server/fvlogging/datalog/templates/datalog/base.html
{% extends "base.html" %}

server/fvlogging/datalog/templates/datalog/detail.html
{% extends "datalog/base.html" %}
{% block content %}
<header>{{controller.description}}</header>

<section>
<form action="" method="post">{% csrf_token %}
  <table class="RegisterTable">
    <tr>
      <th>Register</th><th>Value</th><th>New value</th><th>Last changed</th>
{% if not config %}
      <th>Future value</th><th>Apply after</th>
{% endif %}
    </tr>
{% for r in registers %}
    <tr><td>{{r.description}}</td><td>{{r.value}}{{r.unit}}</td>
      <td>{% if not r.readonly %}
	<input type="text" name="{{r.name}}" id="td_{{r.name}}" />
	{% endif %}</td>
      <td>{{r.last_change}}</td>
{% if not config %}
      <td>{% if r.future_value %}{{r.future_value}}{% endif %}</td>
      <td>{% if r.future_time %}{{r.future_time}}{% endif %}</td>
{% endif %}
    </tr>
{% endfor %}
  </table>
{% if not config %}
{{fcform.as_p}}
  <script type="text/javascript">
var dtpicker_options = {firstDay: 1,
  dateFormat: 'yy-mm-dd', timeFormat: 'hh:mm:ss'}
$(document).ready(function(){
 $("#id_after").datetimepicker(dtpicker_options);
})
  </script>
{% endif %}
  <button type="submit" name="set">Alter registers</button>
{% if not config %}
  <button type="submit" name="clear">Clear future values</button>
{% endif %}
</form>

{% if not config %}<p><a href="{% url "datalog-controller-config" controller.ident %}">Click here for configuration registers</a></p>{% endif %}
</section>

{% if not config %}
<section>
<a href="{% url "datalog-detailgraph" controller.ident %}">
<p>Last 7 days:</p>
<img src="{% url "datalog-graph" %}?{% for reg in controller.register_set.all %}{% if reg.graphcolour %}series={{reg.controller.ident}}:{{reg.name}}:{{reg.graphcolour}}&amp;{% endif %}{% endfor %}{% for reg in extraseries %}series={{reg.controller.ident}}:{{reg.name}}:{{reg.graphcolour_all}}&amp;{% endfor %}start=7&amp;leftmargin=0&amp;bottommargin=0"></a>
</section>
{% endif %}

{% endblock %}

server/fvlogging/datalog/templates/datalog/detailgraph.html
{% extends "datalog/base.html" %}
{% block content %}
<header>{{controller.description}}</header>

<img src="{% url "datalog-graph" %}?{% for reg in controller.register_set.all %}{% if reg.graphcolour %}series={{reg.controller.ident}}:{{reg.name}}:{{reg.graphcolour}}&amp;{% endif %}{% endfor %}{% for reg in extraseries %}series={{reg.controller.ident}}:{{reg.name}}:{{reg.graphcolour_all}}&amp;{% endfor %}start={{start}}&amp;end={{end}}&amp;leftmargin=0&amp;bottommargin=0">

<form action="" method="post" class="graphperiodform">
{% csrf_token %}
<ul>{{form.as_ul}}</ul>
<input type="submit" value="Go">
</form>

<ul>
<li><a href="{% url "datalog-detailgraph-period" controller.ident back start %}">Back {{period}}</a></li>
<li><a href="{% url "datalog-detailgraph-period" controller.ident end forward %}">Forward {{period}}</a></li>
<li><a href="{% url "datalog-detailgraph" controller.ident %}">Most recent 7 days</a></li>
<li><a href="{% url "datalog-controller" controller.ident %}">Back to {{controller.description}} registers page</a></li>
</ul>

<script type="text/javascript">
var dtpicker_options = {firstDay: 1,
  dateFormat: 'yy-mm-dd', timeFormat: 'hh:mm:ss'}
$(document).ready(function(){
 $("#id_start").datetimepicker(dtpicker_options);
 $("#id_end").datetimepicker(dtpicker_options);
})
</script>

{% endblock %}

server/fvlogging/datalog/templates/datalog/summary.html
{% extends "datalog/base.html" %}
{% block jquery %}{% endblock %}
{% block content %}
<header>Data log</header>
{% if controllers %}
<section>
<table class="RegisterTable">
<tr><th>Vessel</th><th>Temperature</th><th>Mode</th><th>Low</th><th>High</th><th>Valve</th><th>Alarm</th><th></th></tr>
{% for c in controllers %}
<tr>
<td><a href="{{c.get_absolute_url}}">{{c.ident}}</a></td>
<td>{{c.regs.t0.value}}{{c.regs.t0.unit}}</td>
<td>{{c.regs.mode.value}}</td>
<td>{{c.regs.setlo.value}}{{c.regs.setlo.unit}}</td>
<td>{{c.regs.sethi.value}}{{c.regs.sethi.unit}}</td>
<td>{{c.regs.v0.value}}</td>
<td>{{c.regs.alarm.value}}</td>
<td><a href="{% url "datalog-csvfile" c.ident "t0" %}">Download CSV</a></td>
</tr>
{% endfor %}
</table>
</section>
{% endif %}

{% if registers %}
<br />
<table>
{% for r in registers %}
<tr>
<td>{{r.description}}</td>
<td>{{r.value}}{{r.unit}}</td>
<td><a href="{% url "datalog-graph" %}?series={{r.controller.ident}}:{{r.name}}:black&amp;start=7&amp;leftmargin=0&amp;bottommargin=0">Graph</a></td>
</tr>
{% endfor %}
</table>
{% endif %}

{% endblock %}